#!/usr/bin/env python3
"""Audit what an ALFWorld V3 query is and how its splits overlap."""

from __future__ import annotations

import json
import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
PHASES = ROOT / "data/alfworld_task_skill/task_skill_v3_phase/phases/phases.jsonl"
MANIFEST = ROOT / "data/alfworld_task_skill/task_skill_v3_phase/manifests/source_manifest.json"
SPLIT_REPORT = ROOT / "data/alfworld_task_skill/task_skill_v3_phase/manifests/split_report.json"
OUTPUT = ROOT / "artifacts/alfworld_ncf/v3_query_overlap_audit.json"
SPLITS = ("train", "dev", "test")


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def normalize(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip().lower())


def overlap_table(rows: list[dict[str, Any]], field: str) -> dict[str, Any]:
    values = {
        split: {normalize(row[field]) for row in rows if row["internal_split"] == split}
        for split in SPLITS
    }
    pairs: dict[str, Any] = {}
    for left, right in (("train", "dev"), ("train", "test"), ("dev", "test")):
        overlap = sorted(values[left] & values[right])
        pairs[f"{left}_vs_{right}"] = {
            "exact_normalized_overlap": len(overlap),
            "examples": overlap[:10],
        }
    return {"unique_by_split": {split: len(values[split]) for split in SPLITS}, "pairs": pairs}


def main() -> None:
    rows = load_jsonl(PHASES)
    manifest = load_json(MANIFEST)
    split_report = load_json(SPLIT_REPORT)
    result = {
        "schema_version": "skilldag_ncf.v3.query_overlap_audit.v1",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "definitions": {
            "raw_full_task": "First ALFWorld annotation task_desc selected from official traj_data.json.",
            "canonical_full_task": "Deterministic task goal generated from task_type and PDDL goal parameters.",
            "phase_query": "Deterministic short macro-step intent generated by build_phase_specs; it is not copied from a trajectory or expert plan.",
            "context_text": "Actual V3 retrieval input: raw task + canonical goal + task type + current phase/query + structured entities and state.",
        },
        "source_policy": manifest["selection_policy"],
        "counts": {
            "tasks": sum(len(manifest["record_ids"][split]) for split in SPLITS),
            "phases": len(rows),
            "phases_by_split": dict(sorted(Counter(row["internal_split"] for row in rows).items())),
        },
        "overlap": {
            field: overlap_table(rows, field)
            for field in ("raw_full_task", "canonical_full_task", "phase_query", "context_text")
        },
        "leakage_checks": {
            "record_id_overlap_across_internal_splits": split_report["record_id_overlap_across_internal_splits"],
            "task_text_hash_overlap_across_internal_splits": split_report["task_text_hash_overlap_across_internal_splits"],
            "forbidden_record_id_overlap": split_report["forbidden_record_id_overlap"],
            "forbidden_task_text_hash_overlap": split_report["forbidden_task_text_hash_overlap"],
            "official_evaluation_splits": ["valid_train", "valid_seen", "valid_unseen"],
        },
        "interpretation": {
            "direct_task_leakage": False,
            "phase_query_reuse": True,
            "phase_query_reuse_meaning": "Different tasks can share generic subgoals such as find apple or verify object in receptacle. This is same-domain compositional generalization, not exact task leakage.",
            "strict_novel_intent_generalization": False,
        },
        "api_calls_made": 0,
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
